services:
  ai-conding-github:
    image: ${IMAGE_REGISTRY:-docker.cnb.cool/ocean-data/dontcry/ai-coding}:${IMAGE_TAG:-latest}
    container_name: ai-conding-github
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./data:/data
      - ./logs:/app/logs
